import traceback

try:
    from urllib3.packages.six.moves import urllib
except Exception:
    traceback.print_exc()